[package]
name = "smorupy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "smorupy"
crate-type = ["cdylib"]

[dependencies]
smorust = { path = "../smorust" }
pyo3 = { version = "0.20", features = ["extension-module"] }
numpy = "0.20"